# -*- coding: utf-8 -*-

"""
xero

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from xero.api_helper import APIHelper
from xero.configuration import Server
from xero.controllers.base_controller import BaseController
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from xero.http.http_method_enum import HttpMethodEnum
from apimatic_core.authentication.multiple.single_auth import Single
from xero.models.success_return_response_of_type_cis_settings_for_a_specific_contact import SuccessReturnResponseOfTypeCISSettingsForASpecificContact
from xero.exceptions.a_failed_request_due_to_validation_error_exception import AFailedRequestDueToValidationErrorException


class ContactIDController(BaseController):

    """A Controller to access Endpoints in the xero API."""
    def __init__(self, config):
        super(ContactIDController, self).__init__(config)

    def allows_you_to_retrieve_a_single_contacts_in_a_xero_organisation(self,
                                                                        contact_id,
                                                                        xero_tenant_id):
        """Does a GET request to /Contacts/{ContactID}.

        Args:
            contact_id (str): (Required) Unique identifier for a Contact
            xero_tenant_id (str): (Required) Xero identifier for Tenant

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Contacts/{ContactID}')
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                            .key('ContactID')
                            .value(contact_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
        ).execute()

    def update_contact(self,
                       contact_id,
                       xero_tenant_id,
                       body):
        """Does a POST request to /Contacts/{ContactID}.

        Args:
            contact_id (str): (Required) Unique identifier for a Contact
            xero_tenant_id (str): (Required) Xero identifier for Tenant
            body (UpdateContactRequest): The request body parameter.

        Returns:
            str: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Contacts/{ContactID}')
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                            .key('ContactID')
                            .value(contact_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .header_param(Parameter()
                          .key('Content-Type')
                          .value('application/json'))
            .body_param(Parameter()
                        .value(body))
            .body_serializer(APIHelper.json_serialize)
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .local_error('400', 'Bad Request', AFailedRequestDueToValidationErrorException)
        ).execute()

    def allows_you_to_retrieve_cis_settings_for_a_contact_in_a_xero_organisation(self,
                                                                                 contact_id,
                                                                                 xero_tenant_id):
        """Does a GET request to /Contacts/{ContactID}/CISSettings.

        Args:
            contact_id (str): (Required) Unique identifier for a Contact
            xero_tenant_id (str): (Required) Xero identifier for Tenant

        Returns:
            SuccessReturnResponseOfTypeCISSettingsForASpecificContact:
                Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER_1)
            .path('/Contacts/{ContactID}/CISSettings')
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                            .key('ContactID')
                            .value(contact_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key('xero-tenant-id')
                          .value(xero_tenant_id))
            .header_param(Parameter()
                          .key('accept')
                          .value('application/json'))
            .auth(Single('oauth2'))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(SuccessReturnResponseOfTypeCISSettingsForASpecificContact.from_dictionary)
        ).execute()
